export const LOGIN_SUCCESS = "LOGIN_SUCCES";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const PROFILE_SUCCESS = "PROFILE_SUCCESS";
export const PROFILE_FAILURE = "PROFILE_FAILURE";

export const POST_PINJAMAN_SUCCESS = "POST_PINJAMAN_SUCCESS";
export const POST_PINJAMAN_FAILURE = "POST_PINJAMAN_FAILURE";

export const GET_PINJAMAN_SUCCESS = "GET_PINJAMAN_SUCCESS";
export const GET_PINJAMAN_FAILURE = "GET_PINJAMAN_FAILURE";

export const GET_MEMBER_SUCCESS = "GET_MEMBER_SUCCESS";
export const GET_MEMBER_FAILURE = "GET_MEMBER_FAILURE";

export const GET_ANGSURAN_SUCCESS = "GET_ANGSURAN_SUCCESS";
export const GET_ANGSURAN_FAILURE = "GET_ANGSURAN_FAILURE";

export const GET_SIMPANAN_SUCCESS = "GET_SIMPANAN_SUCCESS";
export const GET_SIMPANAN_FAILURE = "GET_SIMPANAN_FAILURE";

export const POST_SIMPANAN_SUCCESS = "POST_SIMPANAN_SUCCESS";
export const POST_SIMPANAN_FAILURE = "POST_SIMPANAN_FAILURE";