export const GET = "GET";
export const POST = "POST";
export const POSTNOTOKEN = "POSTNOTOKEN";
export const PUT = "PUT";
export const PATCH = "PATCH";
export const DELETE = "DELETE";
export const UPLOAD = "UPLOAD";
export const API_URL = "https://api.arnawa.co.id/api";
// export const API_URL2 = "https://simpin.arnintech.co.id/api/mobile";
export const API_URL2 = "https://simpin2.arnintech.co.id"